### ISSUE TITLE
Pipeline configuration

### ISSUE THREAD

**Issue by drewwells** [armory/spinnaker-kustomize-patches#40]
Part of using spinnaker is configuration the pipelines themselves. How does the operator configure pipelines?

**Comment by devorbitus** [comment]
The short answer is that it doesn't. Think of Spinnaker operator as an advanced halyard config file reader that makes sure the deployed Spinnaker deployment is matching the prescribed parameters. There really isn't a way for standart halyard to make pipelines on it's own and operator currently uses halyard under the hood.
