### ISSUE TITLE
Does the readme need a disclaimer?

### ISSUE THREAD

**Issue by MichaelDBrown** [armory/spinnaker-kustomize-patches#8]
Is this repo supported Armory code or is it community supported? We probably need to make that clearer in the README before we share this broadly with customers.

**Comment by german-muzquiz** [comment]
I think that since this is a public repo community contributions are welcome, but Armory would review and merge them.
We can add a disclaimer stating that these are example configurations, and that they need to be adjusted appropriately for each specific installation.

**Comment by MichaelDBrown** [comment]
got it, I agree. I like the new disclaimer. Thanks!
